### ISSUE TITLE
Policy proposal: allow subsequent tasks to change TCAs

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#607] opened 2022-05-23 13:29 UTC
At the moment, each task writes out their TClonesArray and it mostly is not changed subsequently. 

While this seems reasonable, it also has some unintended consequences. 

Exhibit 0: https://github.com/R3BRootGroup/R3BRoot/blob/dev/califa/calibration/R3BCalifaCrystalCal2Hit.cxx#L287

As the name of that class (if it was called R3BCalifaCrystalCal2Cluster) clearly states, this file is the clustering code. Smearing to avoid binning effects is clearly not part of clustering. 

If we adopted the policy that subsequent tasks may write to a TCA, it would be trivial to move the code to a separate class called R3BCalifaClusterSmearer or something. I am rather philosophically opposed to the way the smearing (actually it's rather the opposite) is done in any case, but if we have to have that code, I would rather have it separately somewhere.

As a different example, I have a beam-based lorentz unboosting code somewhere in the pipeline. While I would argue that this is useful, it is clearly not related to clustering and should not be part of the clustering task. My idea there would be to simply add a few more fields in the HitData which are NAN-initialized in the Cal2Hit and can be filled out by a subsequent task. 

Alternatives:
* Copy desired changes to a new TCA with a different name (e.g. for smearing): 
     * While we should support this, having to pass TCA names to every task should not be required as a default
* Add a new Data member for new fields written later (e.g. for Ion Frame energies):
     * Will require juggling more TCAs, which is painful, and will require lookups between TCAs. 

The preexisting clustering task is not going to win any prizes for code beauty as it is, but this way we could avoid it turning into something like R3BCalifaOnlineSpectra at least. 

What do you think?

**Comment by gabrigarjim** [comment] 2022-05-23 14:33
In general I would agree with your point of view. Maybe it is a better idea to keep the cluster as it comes from CALIFA and then make as many desired modifications in that data afterwards. On the other hand, the randomization procedure can be set to false and then you will obtain the "normal"  clusters, with discrete angles. The two options are fine for me , but :

1. Some changes to the Hit level  and Cal2Hit task are needed . First of all , I would like to have a Mother Crystal Id inside each cluster, and also a list of crystal id's that form that cluster (this can be merged into one single list, being the first entry in this list the crystal that is chosen as a cluster candidate)
2. As I mentioned before in other issue (https://github.com/R3BRootGroup/R3BRoot/issues/549, now closed, because no one answered) the clustering procedure now is not prepared for the high multiplicity we have in most of the experiments. A partial remake of that class would be needed (I volunteer myself to start with that)
3. I completely agree with the fact that this code rather difficult to follow. I have the strong opinion that if a code is long but simple , and works as it should be is better than a short, elegant code that nobody can follow. Each year we have new people approaching r3broot. The guy making the code is only going to read it once or twice, but will be readed by a lot of people. So simple, clear and well documented is better.  
The way I see it, our code must be efficient , clear and work as intended, but in my humble opinion we are physicists using the software as a tool for getting physical results, so I really don't mind if we are not following std C++23 or whatever cool algorithm is the most hyped in reddit.

**Closed** 2023-02-12 00:43 UTC
